version: "3.8"
services:
  server:
    container_name: server
    build:
      context: .
      target: server
    secrets:
      - jwt_key
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
secrets:
  jwt_key:
    file: ${JWT_KEY_PATH}
