version: "3.8"
services:
  server:
    container_name: server
    build:
      context: .
      target: server
    secrets:
      - jwt_key
      - ca_cert
      - server_cert
      - server_key
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
secrets:
  jwt_key:
    file: ${JWT_KEY_PATH}
  ca_cert:
    file: ${CA_CERT_PATH}
  server_cert:
    file: ${SERVER_CERT_PATH}
  server_key:
    file: ${SERVER_KEY_PATH}
